// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7zpJrb1Ngo7KB0g155u_PWKJC7fw_-o',
    appId: '1:1057982567529:web:6d5dd88bf367489aaa3ef8',
    messagingSenderId: '1057982567529',
    projectId: 'helper-92613',
    authDomain: 'helper-92613.firebaseapp.com',
    databaseURL: 'https://helper-92613.firebaseio.com',
    storageBucket: 'helper-92613.firebasestorage.app',
    measurementId: 'G-3D2KSM63GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq872QoXPx3fPwC73zjAHD-6SzSAhr84Y',
    appId: '1:1057982567529:android:7867bbfe2d3620f5aa3ef8',
    messagingSenderId: '1057982567529',
    projectId: 'helper-92613',
    databaseURL: 'https://helper-92613.firebaseio.com',
    storageBucket: 'helper-92613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjW7AqgPBRIuHDcn0Ijw8_eMHOahwfLs',
    appId: '1:1057982567529:ios:3c42d3bda4114760aa3ef8',
    messagingSenderId: '1057982567529',
    projectId: 'helper-92613',
    databaseURL: 'https://helper-92613.firebaseio.com',
    storageBucket: 'helper-92613.firebasestorage.app',
    iosBundleId: 'com.example.projetIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjW7AqgPBRIuHDcn0Ijw8_eMHOahwfLs',
    appId: '1:1057982567529:ios:3c42d3bda4114760aa3ef8',
    messagingSenderId: '1057982567529',
    projectId: 'helper-92613',
    databaseURL: 'https://helper-92613.firebaseio.com',
    storageBucket: 'helper-92613.firebasestorage.app',
    iosBundleId: 'com.example.projetIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7zpJrb1Ngo7KB0g155u_PWKJC7fw_-o',
    appId: '1:1057982567529:web:88b249032d72e1bfaa3ef8',
    messagingSenderId: '1057982567529',
    projectId: 'helper-92613',
    authDomain: 'helper-92613.firebaseapp.com',
    databaseURL: 'https://helper-92613.firebaseio.com',
    storageBucket: 'helper-92613.firebasestorage.app',
    measurementId: 'G-VQH1ZML0LR',
  );
}
